# Generated by Django 4.2.7 on 2025-12-15 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('profit_share_pct', models.DecimalField(decimal_places=2, help_text='Client share of profits (%)', max_digits=5)),
                ('loss_share_pct', models.DecimalField(decimal_places=2, help_text='Client share of losses (%)', max_digits=5)),
                ('company_share_pct', models.DecimalField(decimal_places=2, help_text='Company share from your profit (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='core.client')),
            ],
            options={
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('FUNDING', 'Funding (You give money to client)'), ('PROFIT', 'Profit'), ('LOSS', 'Loss'), ('SETTLEMENT', 'Settlement / Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('client_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('your_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company_share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.exchange')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyShareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('company_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_shares', to='core.exchange')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_shares', to='core.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_funding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client_net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('you_net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('company_net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_client_owes_you', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_you_owe_client', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.client')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.exchange')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('client', 'exchange', 'date')},
            },
        ),
    ]
