# Generated by Django 4.2.7 on 2026-01-07 17:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('referred_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_company_client', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_balance', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('my_percentage', models.IntegerField(default=0, help_text='Your total percentage share (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to='core.client')),
            ],
            options={
                'ordering': ['client__name', 'exchange__name'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('FUNDING', 'Funding'), ('TRADE', 'Trade'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('amount', models.BigIntegerField(help_text='Amount in smallest currency unit')),
                ('exchange_balance_after', models.BigIntegerField(help_text='Exchange balance after this transaction (for audit)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('client_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.clientexchangeaccount')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClientExchangeReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend_percentage', models.IntegerField(default=0, help_text='Friend/Student percentage (report only)', validators=[django.core.validators.MinValueValidator(0)])),
                ('my_own_percentage', models.IntegerField(default=0, help_text='Your own percentage (report only)', validators=[django.core.validators.MinValueValidator(0)])),
                ('client_exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_config', to='core.clientexchangeaccount')),
            ],
            options={
                'verbose_name': 'Report Configuration',
                'verbose_name_plural': 'Report Configurations',
            },
        ),
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to='core.exchange'),
        ),
        migrations.AlterUniqueTogether(
            name='clientexchangeaccount',
            unique_together={('client', 'exchange')},
        ),
    ]
