# Generated by Django 4.2.7 on 2026-01-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('FUNDING', 'Funding'), ('TRADE', 'Trade'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment'), ('PAYMENT', 'Payment')], max_length=20),
        ),
    ]
