# Generated by Django 4.2.7 on 2025-12-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_report_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day of week for auto weekly reports (0=Monday, 6=Sunday)')),
                ('auto_generate_weekly_reports', models.BooleanField(default=False, help_text='Automatically generate weekly reports')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
