# Generated by Django 4.2.7 on 2026-01-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('FUNDING', 'Funding'), ('TRADE', 'Trade'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment'), ('RECORD_PAYMENT', 'Record Payment')], max_length=20),
        ),
    ]
