# Generated by Django 4.2.7 on 2025-12-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='companysharerecord',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange',
        ),
        migrations.AddField(
            model_name='exchange',
            name='code',
            field=models.CharField(blank=True, help_text='Optional exchange code', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ClientExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profit_share_pct', models.DecimalField(decimal_places=2, help_text='Client share of profits (%)', max_digits=5)),
                ('loss_share_pct', models.DecimalField(decimal_places=2, help_text='Client share of losses (%)', max_digits=5)),
                ('company_share_pct', models.DecimalField(decimal_places=2, help_text='Company share from your profit (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_exchanges', to='core.client')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_exchanges', to='core.exchange')),
            ],
            options={
                'ordering': ['client__name', 'exchange__name'],
                'unique_together': {('client', 'exchange')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailybalancesnapshot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='client',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='company_share_pct',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='loss_share_pct',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='profit_share_pct',
        ),
        migrations.AddField(
            model_name='companysharerecord',
            name='client_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_shares', to='core.clientexchange'),
        ),
        migrations.AddField(
            model_name='dailybalancesnapshot',
            name='client_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.clientexchange'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.clientexchange'),
        ),
        migrations.AlterUniqueTogether(
            name='dailybalancesnapshot',
            unique_together={('client_exchange', 'date')},
        ),
        migrations.RemoveField(
            model_name='dailybalancesnapshot',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dailybalancesnapshot',
            name='exchange',
        ),
    ]
