# Generated by Django 4.2.7 on 2026-01-08 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='loss_share_percentage',
            field=models.IntegerField(default=0, help_text='Admin share percentage for losses (0-100). IMMUTABLE once data exists.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='profit_share_percentage',
            field=models.IntegerField(default=0, help_text='Admin share percentage for profits (0-100). Can change anytime, affects only future profits.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='clientexchangeaccount',
            name='my_percentage',
            field=models.IntegerField(default=0, help_text='Your total percentage share (0-100) - DEPRECATED: Use loss_share_percentage and profit_share_percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(help_text='Settlement amount (integer, > 0)', validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this settlement', null=True)),
                ('client_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.clientexchangeaccount')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
