# Generated by Django 4.2.7 on 2025-12-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchange_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientexchange',
            name='loss_share_pct',
        ),
        migrations.RemoveField(
            model_name='clientexchange',
            name='profit_share_pct',
        ),
        migrations.AddField(
            model_name='clientexchange',
            name='my_share_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Your share of profits (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='clientexchange',
            name='company_share_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Company share from your profit (%) - must be less than your share', max_digits=5),
        ),
        migrations.AlterField(
            model_name='companysharerecord',
            name='client_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_shares', to='core.clientexchange'),
        ),
        migrations.AlterField(
            model_name='dailybalancesnapshot',
            name='client_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.clientexchange'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.clientexchange'),
        ),
    ]
