# Generated by Django 4.2.7 on 2026-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_masked_share_settlement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='locked_initial_final_share',
            field=models.BigIntegerField(blank=True, default=0, help_text='Initial FinalShare locked at start of PnL cycle. Used for remaining calculation.', null=True),
        ),
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='locked_initial_pnl',
            field=models.BigIntegerField(blank=True, default=0, help_text='Initial PnL when share was locked. Used to detect PnL cycle changes.', null=True),
        ),
        migrations.AddField(
            model_name='clientexchangeaccount',
            name='locked_share_percentage',
            field=models.IntegerField(blank=True, default=0, help_text='Share percentage locked at start of PnL cycle. Prevents historical rewrite.', null=True),
        ),
    ]
