# Generated by Django 4.2.7 on 2025-12-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_clientexchange_loss_share_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientexchange',
            name='company_share_pct',
            field=models.DecimalField(decimal_places=2, help_text='Company share from your profit (%) - must be less than your share', max_digits=5),
        ),
        migrations.AlterField(
            model_name='clientexchange',
            name='my_share_pct',
            field=models.DecimalField(decimal_places=2, help_text='Your share of profits (%)', max_digits=5),
        ),
    ]
