# Generated by Django 4.2.7 on 2025-12-17 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_client_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text="Remaining balance in client's account", max_digits=14)),
                ('note', models.TextField(blank=True, help_text='Optional note about the balance')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='core.client')),
            ],
            options={
                'verbose_name_plural': 'Client Daily Balances',
                'ordering': ['-date'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
