# Generated by Django 4.2.7 on 2026-01-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enforce_exchange_name_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at', 'sequence_no']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_balance_before',
            field=models.BigIntegerField(blank=True, help_text='Exchange balance before this transaction (for audit)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='funding_after',
            field=models.BigIntegerField(blank=True, help_text='Funding after this transaction (for audit)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='funding_before',
            field=models.BigIntegerField(blank=True, help_text='Funding before this transaction (for audit)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sequence_no',
            field=models.IntegerField(default=0, help_text='Sequence number for ordering transactions (auto-increment per account)'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateTimeField(help_text='Date when payment was made'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(help_text='Amount in smallest currency unit (signed, for reporting only)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_balance_after',
            field=models.BigIntegerField(blank=True, help_text='Exchange balance after this transaction (for audit)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('FUNDING_MANUAL', 'Manual Funding'), ('FUNDING_AUTO', 'Auto Re-Funding'), ('TRADE', 'Trade'), ('SETTLEMENT_SHARE', 'Settlement Share Payment'), ('FEE', 'Fee'), ('ADJUSTMENT', 'Adjustment'), ('FUNDING', 'Funding (Legacy)'), ('RECORD_PAYMENT', 'Record Payment (Legacy)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client_exchange', 'created_at', 'sequence_no'], name='core_transa_client__95c1f0_idx'),
        ),
    ]
