# Generated by Django 4.2.7 on 2025-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_company_client',
            field=models.BooleanField(default=False, help_text='If True, this is a company client. If False, this is your personal client.'),
        ),
    ]
