# Generated by Django 4.2.7 on 2025-12-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_is_company_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='admin_loss_pct',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='admin_profit_pct',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='company_share_on_loss_pct',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='company_share_on_profit_pct',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_loss_share_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Admin share percentage of client loss (admin earns this % of loss)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_profit_share_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Admin share percentage of client profit (admin pays this % of profit)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_loss_share_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Company share percentage of client loss (company earns this % of loss)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_profit_share_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Company share percentage of client profit (company pays this % of profit)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='clientexchange',
            name='company_share_pct',
            field=models.DecimalField(decimal_places=2, help_text="Company share percentage FROM CLIENT's share (%). Example: If your share is 30% and company share is 9%, company gets 9% of the client's 70% share. Must be less than 100.", max_digits=5),
        ),
    ]
