# Generated by Django 4.2.7 on 2025-12-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_client_user_alter_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('FUNDING', 'Funding (You give money to client)'), ('PROFIT', 'Profit'), ('LOSS', 'Loss'), ('SETTLEMENT', 'Settlement / Payout'), ('BALANCE_RECORD', 'Balance Record')], max_length=20),
        ),
        migrations.CreateModel(
            name='OutstandingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, help_text='Net outstanding amount (positive = client owes you, negative = you owe client)', max_digits=14)),
                ('note', models.TextField(blank=True, help_text='Optional note about outstanding amount')),
                ('client_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_amounts', to='core.clientexchange')),
            ],
            options={
                'verbose_name_plural': 'Outstanding Amounts',
                'unique_together': {('client_exchange',)},
            },
        ),
    ]
