# Generated by Django 4.2.7 on 2025-12-25 18:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_outstanding_amount_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outstandingamount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='outstandingamount',
            name='client_exchange',
            field=models.OneToOneField(help_text='One outstanding ledger per client-exchange (My Clients only)', on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_amount_ledger', to='core.clientexchange'),
        ),
        migrations.AlterField(
            model_name='outstandingamount',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Net outstanding amount (Your Share only). Positive = client owes you, negative = you owe client (auto-settles)', max_digits=14),
        ),
    ]
