# Generated by Django 4.2.7 on 2025-12-25 19:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_change_outstanding_to_one_to_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_owes_you', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Client owes you (your direct share from losses, e.g., 10% of loss)', max_digits=14)),
                ('company_owes_you', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Company owes you (company's portion from losses, 9% of loss)", max_digits=14)),
                ('you_owe_client', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='You owe client (your direct share from profits, e.g., 10% of profit)', max_digits=14)),
                ('you_owe_company', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="You owe company (company's portion from profits, 9% of profit)", max_digits=14)),
                ('note', models.TextField(blank=True, help_text='Optional note about tally ledger')),
                ('client_exchange', models.OneToOneField(help_text='One tally ledger per client-exchange (Company Clients only)', on_delete=django.db.models.deletion.CASCADE, related_name='tally_ledger', to='core.clientexchange')),
            ],
            options={
                'verbose_name_plural': 'Tally Ledgers',
            },
        ),
    ]
