# Generated by Django 4.2.7 on 2026-01-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_capital_closed_and_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysharerecord',
            name='client_exchange',
        ),
        migrations.RemoveField(
            model_name='companysharerecord',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='tallyledger',
            name='client_exchange',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_user_id_348836_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_is_comp_df7ee4_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_company_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='security_deposit_paid_date',
        ),
        migrations.RemoveField(
            model_name='clientexchange',
            name='company_share_pct',
        ),
        migrations.RemoveField(
            model_name='losssnapshot',
            name='company_share_pct',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company_share_amount',
        ),
        migrations.DeleteModel(
            name='CompanyShareRecord',
        ),
        migrations.DeleteModel(
            name='TallyLedger',
        ),
    ]
